# checks if kubeconfig pointed to correct cluster 
- name: "Reading version info"
  set_fact:
    cluster_info: "{{ lookup('k8s', cluster_info='version') }}"
  ignore_errors: true

- set_fact:
    openshift_version: "{{ cluster_info.openshift }}"
  ignore_errors: true

- when: openshift_version is not defined
  ignore_errors: true
  block:
  - set_fact:
      openshift_version_info: "{{ lookup('k8s', 
        api_version='config.openshift.io/v1', 
        kind='ClusterVersion',
        resource_name='version'
      ) }}"
  
  - set_fact:
      openshift_version: "{{ openshift_version_info.status.desired.version }}"
    when: openshift_version_info.get('status', {}).get('desired', {}).get('version', '') != ''
          
- when: k8s_version is not defined and
        openshift_version is not defined
  fail:
    msg: "You are not logged into an OpenShift cluster. Exiting..."

- when: openshift_version is defined
  debug:  
    msg: |
      {% if openshift_version is defined and openshift_version.major is defined %}
      Detected OpenShift version - {{ openshift_version.major|string + '.' + openshift_version.minor|string }}
      {% elif openshift_version is defined and openshift_version.major is not defined %}
      Detected OpenShift version - {{ openshift_version|string }}
      {% endif %}

- pause:
    prompt: |
      [WARNING] KUBECONFIG should be set to destination cluster (likely OCP 4.x) for 'Stage 2' and 'Stage 3', but OCP 3.x cluster detected.
      
      Please verify the information printed above about the logged in cluster and select an action:
      - Press ENTER to continue
      - Press Ctrl+C and A to abort
  when: openshift_version is not string and 
    openshift_version.get('major', 0)|int == 3